spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/user_address_db
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: create
    show-sql: true